lib/time1_web/router.ex
defmodule Time1Web.Router do
  use Time1Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug Time1Web.Plugs.FetchCurrentUser
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Time1Web do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/timesheets", TimesheetController
    resources "/jobs", JobController
    resources "/tasks", TaskController
    resources "/userselect", UserselectController
    resources "/sessions", SessionController,
      only: [:new, :create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", Time1Web do
  #   pipe_through :api
  # end
end

lib/time1_web/views/layout_view.ex
defmodule Time1Web.LayoutView do
  use Time1Web, :view
end

lib/time1_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Time1 · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app-2d8b32fda59482578bf4e69cc49f6212.css") %>"/>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-sm navbar-light bg-white">
        <div class="col-4">
          <a class="navbar-brand" href="#">Timesheets</a>
        </div>
        <div class="col-8">
          <ul class="navbar-nav mr-auto">
            <%= if @current_user && @current_user.is_manager do %>
              <li class="nav-item active">
                <%= link("Jobs", to: Routes.job_path(@conn, :index)) %>
              </li>
              <li class="nav-item active">
                  <%= link("Timesheets", to: Routes.userselect_path(@conn, :new))%>
              </li>
            <%= else %>
              <li>
                <%= link("Log Your Time", to: Routes.timesheet_path(@conn, :new)) %>
              </li>
            <% end %>
                <%# <a class="nav-link" href="#">All Photos</a> %>
              
            <%# <li class="nav-item">
              <a class="nav-link" href="#">Your Photos</a>
            </li> %>
          </ul>
        </div>
        <div class="col-4" text-light>
          <%= if @current_user do %>
            User: <%= @current_user.name %>
            <br>
            (<%= link("Logout", to: Routes.session_path(@conn, :delete),
              method: :delete) %>)
          <% else %>
            <%= link("Login", to: Routes.session_path(@conn, :new)) %>
          <% end %>
        </div>
      </nav>

       <div class="row">
        <div class="col-12">
          <%= if get_flash(@conn, :info) do %>
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= if get_flash(@conn, :error) do %>
            <p class="alert alert-danger" role="alert">
              <%= get_flash(@conn, :error) %>
            </p>
          <% end %>
        </div>
      </div>

      <%= render @view_module, @view_template, assigns %>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>